const HALF = 0.5;
const BROWSER_VIEWPORT_WIDTH = '100vw';
const BROWSER_DEFAULT_FONT_SIZE = 16;
const FIRST_BREAKPOINT = /^/;

module.exports = {
  HALF,
  BROWSER_VIEWPORT_WIDTH,
  BROWSER_DEFAULT_FONT_SIZE,
  FIRST_BREAKPOINT,
};
